### ISSUE TITLE
Does not follow redirects

### ISSUE THREAD

**Issue by ayush** [lloydmeta/metascraper#14]
Does not seem to be following redirects. For example for url: http://www.nytimes.com/2015/09/23/business/media/the-plot-twist-e-book-sales-slip-and-print-is-far-from-dead.html

```
dispatch.StatusCode: Unexpected response status: 303
	at com.beachape.metascraper.Scraper.extractData(Scraper.scala:67) ~[metascraper_2.11-0.2.8.jar:0.2.8]
	at com.beachape.metascraper.Scraper$$anonfun$fetch$1.apply(Scraper.scala:41) ~[metascraper_2.11-0.2.8.jar:0.2.8]
	at com.beachape.metascraper.Scraper$$anonfun$fetch$1.apply(Scraper.scala:41) ~[metascraper_2.11-0.2.8.jar:0.2.8]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]

```

**Comment by lloydmeta** [comment]
Interesting, I'm fairly certain that following redirects work (or did at one point) for 301 and 302s, but maybe the underlying client doesn't support following 303 when the initial request was not a POST/PUT/DELETE?

At the very least, the client is set to [follow redirects](https://github.com/lloydmeta/metascraper/blob/master/src/main/scala/com/beachape/metascraper/ScraperActor.scala#L69)

```scala
.setFollowRedirects(followRedirects).build
```

I'm a bit bogged down with other work at the moment, so any help would be appreciated :)

**Comment by lloydmeta** [comment]
Hi @ayush 

I finally got some time to look at this again, and I think with the latest release, perhaps due to upgrades to the underlying client, this is now fixed ([this added test passes](https://github.com/lloydmeta/metascraper/commit/bd859513e49c452eec3dca647ef529d076463577))

As a result, I'll be closing this issue for now :)

**Comment by ayush** [comment]
Thanks @lloydmeta
