### ISSUE TITLE
Tries to parse non-HTML mime types

### ISSUE THREAD

**Issue by alaz** [lloydmeta/metascraper#15]
For example, it's possible to ask scraper to parse large PDF file or executable. The result makes no sense, but the app will consume a lot of memory

**Comment by lloydmeta** [comment]
Good point! [The latest release](https://github.com/lloydmeta/metascraper/releases/tag/v0.2.9) fixes this issue by looking at the Content-Type of the response to see if it should parse the response or not.

**Comment by alaz** [comment]
Wow, awesome speed!

I just would like to dig into more details here, because we've bumped into this problem in our application. Your fix provides a check **after** the content has already been downloaded, so bandwidth/time was already wasted.

What I've implemented in our app is to check as soon as the headers are received, here it the code excerpt:

```scala
  object Http extends dispatch.Http {

    class PickyFunctionHandler(url: String) extends FunctionHandler[Response](identity) {
      override def onHeadersReceived(headers: HttpResponseHeaders): AsyncHandler.STATE =
        // Don't ever load improper content types or too big content lengths.
        // `onHeadersReceived` phase lets us abort the download early.
        (headers.getHeaders.getFirstValue(HeaderNames.CONTENT_TYPE), headers.getHeaders.getFirstValue(HeaderNames.CONTENT_LENGTH)) match {
          case (null, _) =>
            logger.debug(s"aborting $url download, no headers")
            STATE.ABORT

          case (contentType, null) if contentType.startsWith(MimeTypes.HTML) =>
            super.onHeadersReceived(headers)

          case (contentType, AsLong(contentLength)) if contentType.startsWith(MimeTypes.HTML) && contentLength < LengthLimit =>
            super.onHeadersReceived(headers)

          case _ =>
            logger.debug(s"aborting $url download, Content-Type = ${headers.getHeaders.getFirstValue(HeaderNames.CONTENT_TYPE)}, Content-Length = ${headers.getHeaders.getFirstValue(HeaderNames.CONTENT_LENGTH)}")
            STATE.ABORT
        }
    }

    override def apply(req: Req)(implicit executor: ExecutionContext): Future[Response] =
      apply(req.toRequest -> new PickyFunctionHandler(req.url))
  }
```

**Comment by lloydmeta** [comment]
@alaz Cheers :)

That is an awesome suggestion. I didn't know Dispatch/AsyncHttpClient offered a way to hook into the processing at such an early stage ! 

#17 implements your suggestion :)

**Comment by alaz** [comment]
LGTM. Thanks!
