### ISSUE TITLE
Optional dependency on Akka

### ISSUE THREAD

**Issue by alaz** [lloydmeta/metascraper#26]
Hello @lloydmeta ,

The first of all, big thanks to you for your work on this library!

I am wondering if it would be viable to make dependency on Akka optional? In fact `ScraperActor` is the only component that depends on Akka, and all the rest of "metascraper" doesn't. Specifically, I am not using `ScraperActor` in my application.

The sad truth about Akka is that it's a kind of platform (vs. a library) and thus conflicting dependences on it result in build warnings (eviction), and finally in runtime errors.

Regards,
Alexander

**Comment by lloydmeta** [comment]
Hi @alaz !

Yes absolutely, it is possible. This lib was written a long time ago, back when I was still unfamiliar with Scala and was exploring Akka and actors in general. In fact, in retrospect, it is completely unnecessary and it is safe to remove `ScraperActor` completely from this project and bump the major version.

Do you want to put together such a PR?

**Comment by alaz** [comment]
Great, thanks! I shall submit a PR.
